language: en

pipeline: "pretrained_embeddings_spacy"

policies:
  - name: KerasPolicy
    epochs: 45
  - name: MemoizationPolicy
  - name: FallbackPolicy
    fallback_action_name: 'utter_default'
  - name: FormPolicy